---
- name: Get load-balancer tags for {{ _elbv2_name }}
  command: >-
    aws elbv2 --region={{ _region }} describe-tags --resource-arns={{ _elbv2_arn }}
  changed_when: false
  register: r_ec2_elbv2_tags

- name: Remove elb {{ _elbv2_name }}
  command: >-
    aws elbv2 --region={{ _region }} delete-load-balancer --load-balancer-arn={{ _elbv2_arn }}
  when: _cluster_tag and _cluster_tag[22:] in _cluster_ids
  vars:
    _cluster_tag: >-
      {{ r_ec2_elbv2_tags.stdout | from_json | json_query("TagDescriptions[0].Tags[?starts_with(Key, 'kubernetes.io/cluster/')].Key|[0]") }}
