---
- name: Get route53 hosted zones
  command: aws route53 list-hosted-zones
  changed_when: false
  register: r_route53_hosted_zones

- name: Check route53 hosted zones
  include_tasks: check_route53_hosted_zone.yaml
  loop: >-
    {{ r_route53_hosted_zones.stdout | from_json | json_query('HostedZones') }}
  loop_control:
    loop_var: _route53_hosted_zone
    label: "{{ _route53_hosted_zone_name }}"
  vars:
    _cluster_name: >-
      {{ _route53_hosted_zone_name | regex_replace('^(cluster-)?([^.]+).*', '\2') }}
    _route53_hosted_zone_name: "{{ _route53_hosted_zone.Name }}"
    _route53_hosted_zone_id: "{{ _route53_hosted_zone.Id.split('/')[2] }}"
  when: _cluster_name in _cluster_names
