---
- name: Get ec2 instances
  command: >-
    aws ec2 --region={{ _region }} describe-instances
    --filters "Name=tag-key,Values={% for _cluster_id in _cluster_ids %}{% if not loop.first %},{% endif %}kubernetes.io/cluster/{{ _cluster_id }}{% endfor %}"
  changed_when: false
  register: r_ec2_instances

- name: Terminate ec2 instances
  command: >-
    aws ec2 --region={{ _region }} terminate-instances --instance-ids {{ _ec2_instance_ids | join(' ') }}
  vars:
    _ec2_instance_ids: "{{ r_ec2_instances.stdout | from_json | json_query('Reservations[].Instances[].InstanceId') }}"
  when: _ec2_instance_ids | length > 0
