---
- name: Get VPCs
  command: >-
    aws ec2 --region={{ _region }} describe-vpcs
    --filter "Name=tag-key,Values={% for _cluster_id in _cluster_ids %}{% if not loop.first %},{% endif %}kubernetes.io/cluster/{{ _cluster_id }}{% endfor %}"
  changed_when: false
  register: r_ec2_vpcs

- name: Clean-up VPC
  include_tasks: cleanup_vpc.yaml
  loop: >-
    {{ r_ec2_vpcs.stdout | from_json | json_query('Vpcs') }}
  loop_control:
    loop_var: _vpc
    label: "{{ _vpc_name }}"
  vars:
    _vpc_id: "{{ _vpc.VpcId }}"
    _vpc_name: "{{ _vpc | json_query(_name_tag_query) }}"
    _vpc_cluster_tag: "{{ _vpc | json_query(_cluster_tag_query) }}"
    _name_tag_query: "Tags[?Key=='Name'].Value|[0]"
    _cluster_tag_query: "InternetGateways[0].Tags[?starts_with(Key,'kubernetes.io/cluster/')].Key|[0]"
